name: dishonesty
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python>=3.10
  - pytest
  # CUDA stuff
  - pytorch-cuda=12.1
  - pytorch>=2.1.1
  # Libraries
  - scikit-learn
  # Jupyter and plotting stuff
  - jupyter
  - ipykernel
  - ipywidgets
  - nbformat>=4.2.0  # for plotly
  - plotly
  - seaborn
  # Pip stuff
  - pip
  - pip:
    - transformer-lens
    - git+https://github.com/callummcdougall/CircuitsVis.git#subdirectory=python
    - git+https://github.com/andyzoujm/representation-engineering.git
    - kaleido
